### ISSUE TITLE
Refactor to allow building against a system SWORD installation

### ISSUE THREAD

**Issue by alerque** [tobias-klein/node-sword-interface#3]
The nested build/install if SWORD inside this module is a problem for distro packaging. I'm currently fudging the rules on Arch Linux to have Ezra Project packaged at all, and I would like to use this package for other things as well.

Please add a way to build this linking to a system installed version of the SWORD library rather than building its own. That way this package can be _just_ the interface, not a duplicate of SWORD.

(Extracted from https://github.com/tobias-klein/ezra-project/issues/21).

**Comment by tobias-klein** [comment]
Would it work for you to steer this behavior with an environment variable? So, if that environment variable would be set before `npm install`, then the gyp build system would link against the system SWORD library.

**Comment by alerque** [comment]
Yes I think that would work. It's not ideal, but then again nothing `npm` does is ;-) I can't think of a better suggestion right now.

**Comment by tobias-klein** [comment]
@alerque I added you as collaborator. Once you've accepted the invitation I can assign you as reviewer for the pull request that addresses this issue.

**Comment by alerque** [comment]
@tobias-klein Accepted.
