### ISSUE TITLE
License compliance

### ISSUE THREAD

**Issue by bgermann** [tobias-klein/node-sword-interface#8]
node-sword-interface is licensed under GPLv3+ while sword, which your work is a derivative work of, is licensed under GPLv2 only. It is [well understood](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility) that these licenses are incompatible. Would you please relicense to a compatible license so that one can distribute builds of node-sword-interface binaries without the risk of being sued by CrossWire? A good choice keeping your current version license compatible with a relicensed version would be GPLv2+. Another solution would be asking CrossWire to relicense sword to GPLv2+ but that would be a heavy project for them given the number of contributors who would have to agree to that change.

**Comment by tobias-klein** [comment]
Thanks for highlighting this! I understand that this is a necessary change. I'll fix this in the next release!

**Comment by bgermann** [comment]
Please note that the same goes for ezra-project because that is a derivative work of sword via node-sword-interface.

**Comment by alerque** [comment]
I don't think the same goes for Ezra. Not everything that uses the API interface needs to have the same license as the software that provides the interface.

**Comment by bgermann** [comment]
IANAL but it would be a good change to e on the legally safe side.

**Comment by alerque** [comment]
You don't have to be a lawyer to confirm that it's okay to build a GPL3 app that uses GLP2 libraries and be legally safe. The license for the SWORD library must be included with the distribution and any modifications of SWORD itself would need to be under its license, but apps that **use** the library API are under no legal obligation to match licenses.

**Comment by bgermann** [comment]
That is not obvious. The link that I provided has this in the compatibility matrix:
I want to license my code under: GPLv3 or later
I want to use a library under: GPLv2 only
Result: NO

**Comment by bgermann** [comment]
* That is what is called "viral" for the GPL.
